### ISSUE TITLE
Test fails with java.lang.UnsatisfiedLinkError (Can't find dependent libraries)

### ISSUE THREAD

**Issue by florint1** [gonzus/jnano#10]
Executing **ant -Dcn=org.nanomsg.Tester run** under Windows fails with an java.lang.UnsatisfiedLinkError error.

Any idea how to overcome this? If I write a little test program myself I get the same error. When I drop nanomsg.dll in java bin\folder the VM crashes.

Thanks!!

Here is the output of the test command:

Buildfile: c:\projects_local\jnano\build.xml

init:

load.win.properties:
     [echo] Loading addtional properties from: build.windows.properties

load.unix.properties:

init.properties:
     [echo] dir.nano.lib=C:\Program Files (x86)\nanomsg\lib
     [echo] dir.nano.libname=nanomsg
     [echo] dir.jni.headers=C:\Program Files (x86)\Java\jdk1.8.0_111\include

create.dirs:

compile.main:

jar.main:

jni.genh:

jni.geno:

init:

load.win.properties:
     [echo] Loading addtional properties from: build.windows.properties

load.unix.properties:

init.properties:
     [echo] dir.nano.lib=C:\Program Files (x86)\nanomsg\lib
     [echo] dir.nano.libname=nanomsg
     [echo] dir.jni.headers=C:\Program Files (x86)\Java\jdk1.8.0_111\include

create.dirs:

compile.main:

jar.main:

jni.genh:

jni.geno.win:
[cpptasks:cc] Starting dependency analysis for 1 files.
[cpptasks:cc] 1 files are up to date.
[cpptasks:cc] 0 files to be recompiled from dependency analysis.
[cpptasks:cc] 0 total files to be compiled.

init:

load.win.properties:
     [echo] Loading addtional properties from: build.windows.properties

load.unix.properties:

init.properties:
     [echo] dir.nano.lib=C:\Program Files (x86)\nanomsg\lib
     [echo] dir.nano.libname=nanomsg
     [echo] dir.jni.headers=C:\Program Files (x86)\Java\jdk1.8.0_111\include

create.dirs:

compile.main:

jar.main:

jni.genh:

jni.geno.unix:

run:
     [java] Starting Tester
     [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\projects_local\jnano\build\c\sharedlibrary\jnano.dll: Can't find dependent libraries
     [java] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [java] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
     [java] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
     [java] 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
     [java] 	at java.lang.System.loadLibrary(System.java:1122)
     [java] 	at org.nanomsg.NanoLibrary.ensureNativeCode(NanoLibrary.java:264)
     [java] 	at org.nanomsg.NanoLibrary.<clinit>(NanoLibrary.java:12)
     [java] 	at org.nanomsg.Tester.allocate(Tester.java:23)
     [java] 	at org.nanomsg.Tester.main(Tester.java:8)

BUILD SUCCESSFUL
Total time: 1 second

**Comment by gonzus** [comment]
Wild guess: did you compile / install the nanomsg library itself? The jnano DLL needs to load the nanomsg DLL (sorry if this is obvious).

**Comment by florint1** [comment]
Hi - yes - I did compile them myself.

I added nanomsg.dll path to the system path and this seemed to solve the error. Placing it under jnano.dll didn't work, only changing the system path did. If you think this is the solution you may close the issue.

**Comment by gonzus** [comment]
Yes, I have a vague memory about the nanomsg DLL having to be in the system path. Windows vagaries... You have to understand it has been years since I did anything with this code. Will close.
