### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION encountered when running the test

### ISSUE THREAD

**Issue by florint1** [gonzus/jnano#11]
Compiled nanomsg, compiled jnano on Windows all without errors.

When running **ant -Dcn=org.nanomsg.Tester run** the JVM Crashes with EXCEPTION_ACCESS_VIOLATION. This is a 64 bit machine, but running JVM 32 bit. I tried compiling nanomsg for 64 bit and ran the above command under 64 bit JVM, same result.

Anyone seen this before? Thanks!!

**Here is how the command executes :**

[java] Starting Tester
     [java] #
     [java] # A fatal error has been detected by the Java Runtime Environment:
     [java] #
     [java] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x55871c44, pid=4028, tid=0x00001b5c
     [java] #
     [java] # JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
     [java] # Java VM: Java HotSpot(TM) Client VM (25.111-b14 mixed mode, sharing windows-x86 )
     [java] # Problematic frame:
     [java] # C  [jnano.dll+0x1c44]
     [java] #
     [java] # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
     [java] #
     [java] # An error report file with more information is saved as:
     [java] # c:\projects_local\jnano32\hs_err_pid4028.log
     [java] #
     [java] # If you would like to submit a bug report, please visit:
     [java] #   http://bugreport.java.com/bugreport/crash.jsp
     [java] # The crash happened outside the Java Virtual Machine in native code.
     [java] # See problematic frame for where to report the bug.
     [java] #

**The aforementioned crash file contains this:** 
(sorry for the long output).

#A fatal error has been detected by the Java Runtime Environment:
#EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x54cc1c44, pid=7620, tid=0x00002074
#JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
#Java VM: Java HotSpot(TM) Client VM (25.111-b14 mixed mode, sharing windows-x86 )
#Problematic frame:
#C  [jnano.dll+0x1c44]
#Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#If you would like to submit a bug report, please visit:
#http://bugreport.java.com/bugreport/crash.jsp
#The crash happened outside the Java Virtual Machine in native code.
#See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x00418800):  JavaThread "main" [_thread_in_native, id=8308, stack(0x00cd0000,0x00d20000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x00000073

Registers:
EAX=0x54c97470, EBX=0x15044118, ECX=0x00000073, EDX=0x00000073
ESP=0x00d1f1cc, EBP=0x00d1f528, ESI=0x15044110, EDI=0x00418800
EIP=0x54cc1c44, EFLAGS=0x00010293

Top of Stack: (sp=0x00d1f1cc)
0x00d1f1cc:   00000073 54c97470 00000000 54c97470
0x00d1f1dc:   000000cb 004affc0 00000000 00000000
0x00d1f1ec:   004affc4 00000000 0043c240 0043c244
0x00d1f1fc:   00000000 0000007d 54c97470 00000000
0x00d1f20c:   54c97480 00000001 54c97490 00000002
0x00d1f21c:   54c974a0 00000003 54c974b0 00000004
0x00d1f22c:   54c974c0 00000005 54c974d4 00000006
0x00d1f23c:   54c974e8 00000007 54c97500 00000008 

Instructions: (pc=0x54cc1c44)
0x54cc1c24:   8d d4 fc ff ff 8b 94 cd e0 fc ff ff 89 95 ac fc
0x54cc1c34:   ff ff 8b 85 b0 fc ff ff 50 8b 4d 08 51 8b 55 08
0x54cc1c44:   8b 02 8b 88 9c 02 00 00 ff d1 89 85 bc fc ff ff
0x54cc1c54:   8b 95 ac fc ff ff 52 8b 85 c4 fc ff ff 50 8b 8d 

Register to memory mapping:

EAX=0x54c97470 is an unknown value
EBX={method} {0x1504411c} 'load_symbols' '(Ljava/util/Map;)I' in 'org/nanomsg/NanoLibrary'
ECX=0x00000073 is an unknown value
EDX=0x00000073 is an unknown value
ESP=0x00d1f1cc is pointing into the stack for thread: 0x00418800
EBP=0x00d1f528 is pointing into the stack for thread: 0x00418800
ESI=0x15044110 is pointing into metadata
EDI=0x00418800 is a thread

Stack: [0x00cd0000,0x00d20000],  sp=0x00d1f1cc,  free space=316k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jnano.dll+0x1c44]
C  [nanomsg.dll+0x579d0]  __rtc_tzz+0xffffffff

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)

[error occurred during error reporting (printing Java stack), id 0xc0000005]

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x004c1800 JavaThread "Service Thread" daemon [_thread_blocked, id=2972, stack(0x15e10000,0x15e60000)]
  0x004ab800 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=6340, stack(0x15cf0000,0x15d40000)]
  0x004aa800 JavaThread "Attach Listener" daemon [_thread_blocked, id=6788, stack(0x15c30000,0x15c80000)]
  0x004a7800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=5748, stack(0x15ab0000,0x15b00000)]
  0x0049c400 JavaThread "Finalizer" daemon [_thread_blocked, id=8284, stack(0x159e0000,0x15a30000)]
  0x0043fc00 JavaThread "Reference Handler" daemon [_thread_blocked, id=1312, stack(0x00e20000,0x00e70000)]
=>0x00418800 JavaThread "main" [_thread_in_native, id=8308, stack(0x00cd0000,0x00d20000)]

Other Threads:
  0x0043b000 VMThread [stack: 0x04770000,0x047c0000] [id=9968]
  0x004dd400 WatcherThread [stack: 0x15d70000,0x15dc0000] [id=10212]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 def new generation   total 4928K, used 739K [0x04800000, 0x04d50000, 0x09d50000)
  eden space 4416K,  16% used [0x04800000, 0x048b8d10, 0x04c50000)
  from space 512K,   0% used [0x04c50000, 0x04c50000, 0x04cd0000)
  to   space 512K,   0% used [0x04cd0000, 0x04cd0000, 0x04d50000)
 tenured generation   total 10944K, used 0K [0x09d50000, 0x0a800000, 0x14800000)
   the space 10944K,   0% used [0x09d50000, 0x09d50000, 0x09d50200, 0x0a800000)
 Metaspace       used 181K, capacity 2276K, committed 2368K, reserved 4480K

Card table byte_map: [0x00d80000,0x00e10000] byte_map_base: 0x00d5c000

Polling page: 0x001a0000

CodeCache: size=32768Kb used=674Kb max_used=674Kb free=32093Kb
 bounds [0x026c0000, 0x02770000, 0x046c0000]
 total_blobs=154 nmethods=16 adapters=70
 compilation: enabled

Compilation events (10 events):
Event: 0.036 Thread 0x004ab800   12             java.lang.AbstractStringBuilder::ensureCapacityInternal (27 bytes)
Event: 0.036 Thread 0x004ab800 nmethod 12 0x027662c8 code [0x027663e0, 0x027665a8]
Event: 0.036 Thread 0x004ab800   13             java.lang.AbstractStringBuilder::append (29 bytes)
Event: 0.037 Thread 0x004ab800 nmethod 13 0x02766688 code [0x027667a0, 0x027669a8]
Event: 0.042 Thread 0x004ab800   14             java.util.Properties$LineReader::readLine (468 bytes)
Event: 0.043 Thread 0x004ab800 nmethod 14 0x02766c88 code [0x02766e10, 0x0276762c]
Event: 0.043 Thread 0x004ab800   15             java.util.Properties::loadConvert (505 bytes)
Event: 0.043 Thread 0x004ab800 nmethod 15 0x02767d48 code [0x02767e90, 0x027682b8]
Event: 0.046 Thread 0x004ab800   16             java.lang.String::length (6 bytes)
Event: 0.046 Thread 0x004ab800 nmethod 16 0x027687c8 code [0x027688c0, 0x02768950]

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Internal exceptions (2 events):
Event: 0.016 Thread 0x00418800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x04807990) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share
Event: 0.016 Thread 0x00418800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x04807c60) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jni.cpp,

Events (10 events):
Event: 0.046 loading class java/util/regex/Pattern$1
Event: 0.046 loading class java/util/regex/Pattern$1 done
Event: 0.046 loading class java/util/regex/Pattern$5
Event: 0.046 loading class java/util/regex/Pattern$5 done
Event: 0.047 loading class java/util/Formatter$FixedString
Event: 0.047 loading class java/util/Formatter$FormatString
Event: 0.047 loading class java/util/Formatter$FormatString done
Event: 0.047 loading class java/util/Formatter$FixedString done
Event: 0.047 loading class org/nanomsg/NanoLibrary
Event: 0.047 loading class org/nanomsg/NanoLibrary done

Dynamic libraries:
0x00fb0000 - 0x00fe3000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\java.exe
0x77bd0000 - 0x77d50000 	C:\windows\SysWOW64\ntdll.dll
0x75b80000 - 0x75c90000 	C:\windows\syswow64\kernel32.dll
0x75fc0000 - 0x76007000 	C:\windows\syswow64\KERNELBASE.dll
0x76010000 - 0x760b1000 	C:\windows\syswow64\ADVAPI32.dll
0x75e60000 - 0x75f0c000 	C:\windows\syswow64\msvcrt.dll
0x75e40000 - 0x75e59000 	C:\windows\SysWOW64\sechost.dll
0x774a0000 - 0x77590000 	C:\windows\syswow64\RPCRT4.dll
0x75520000 - 0x75580000 	C:\windows\syswow64\SspiCli.dll
0x75510000 - 0x7551c000 	C:\windows\syswow64\CRYPTBASE.dll
0x75580000 - 0x75680000 	C:\windows\syswow64\USER32.dll
0x76240000 - 0x762d0000 	C:\windows\syswow64\GDI32.dll
0x75f10000 - 0x75f1a000 	C:\windows\syswow64\LPK.dll
0x76590000 - 0x7662d000 	C:\windows\syswow64\USP10.dll
0x6ed00000 - 0x6ee9e000 	C:\windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\COMCTL32.dll
0x75820000 - 0x75877000 	C:\windows\syswow64\SHLWAPI.dll
0x77440000 - 0x774a0000 	C:\windows\system32\IMM32.DLL
0x75c90000 - 0x75d5c000 	C:\windows\syswow64\MSCTF.dll
0x74ca0000 - 0x74ccb000 	C:\windows\SysWOW64\nvinit.dll
0x74c90000 - 0x74c99000 	C:\windows\system32\VERSION.dll
0x73580000 - 0x73586000 	C:\Program Files (x86)\NVIDIA Corporation\CoProcManager\detoured.dll
0x73550000 - 0x7357a000 	C:\Program Files (x86)\NVIDIA Corporation\CoProcManager\nvd3d9wrap.dll
0x772a0000 - 0x7743d000 	C:\windows\syswow64\SETUPAPI.dll
0x777a0000 - 0x777c7000 	C:\windows\syswow64\CFGMGR32.dll
0x75770000 - 0x757ff000 	C:\windows\syswow64\OLEAUT32.dll
0x75890000 - 0x759ec000 	C:\windows\syswow64\ole32.dll
0x760c0000 - 0x760d2000 	C:\windows\syswow64\DEVOBJ.dll
0x73530000 - 0x7354e000 	C:\Program Files (x86)\NVIDIA Corporation\CoProcManager\nvdxgiwrap.dll
0x55c90000 - 0x55d4f000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\msvcr100.dll
0x558c0000 - 0x55c8d000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\client\jvm.dll
0x736e0000 - 0x736e7000 	C:\windows\system32\WSOCK32.dll
0x75df0000 - 0x75e25000 	C:\windows\syswow64\WS2_32.dll
0x75b70000 - 0x75b76000 	C:\windows\syswow64\NSI.dll
0x746f0000 - 0x74722000 	C:\windows\system32\WINMM.dll
0x75e30000 - 0x75e35000 	C:\windows\syswow64\PSAPI.DLL
0x5ac40000 - 0x5ac4c000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\verify.dll
0x55890000 - 0x558b1000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\java.dll
0x55870000 - 0x55883000 	C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin\zip.dll
0x76630000 - 0x7727b000 	C:\windows\syswow64\SHELL32.dll
0x76230000 - 0x7623b000 	C:\windows\syswow64\profapi.dll
0x54cc0000 - 0x54cc7000 	C:\projects_local\jnano32\build\c\sharedlibrary\jnano.dll
0x54c40000 - 0x54cbd000 	C:\Program Files (x86)\nanomsg\bin\nanomsg.dll
0x73410000 - 0x7344c000 	C:\windows\system32\MSWSOCK.dll
0x54c20000 - 0x54c3c000 	C:\windows\system32\VCRUNTIME140D.dll
0x54aa0000 - 0x54c13000 	C:\windows\system32\ucrtbased.dll
0x54a90000 - 0x54a93000 	C:\windows\system32\api-ms-win-core-timezone-l1-1-0.dll
0x54a80000 - 0x54a83000 	C:\windows\system32\api-ms-win-core-file-l2-1-0.dll
0x54a70000 - 0x54a73000 	C:\windows\system32\api-ms-win-core-localization-l1-2-0.dll
0x73520000 - 0x73523000 	C:\windows\system32\api-ms-win-core-synch-l1-2-0.dll
0x54a60000 - 0x54a63000 	C:\windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
0x54a50000 - 0x54a53000 	C:\windows\system32\api-ms-win-core-file-l1-2-0.dll
0x54a30000 - 0x54a45000 	C:\windows\system32\VCRUNTIME140.dll
0x54a20000 - 0x54a24000 	C:\windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
0x54930000 - 0x54a11000 	C:\windows\system32\ucrtbase.DLL
0x54920000 - 0x54924000 	C:\windows\system32\api-ms-win-crt-string-l1-1-0.dll
0x54910000 - 0x54913000 	C:\windows\system32\api-ms-win-crt-heap-l1-1-0.dll
0x54900000 - 0x54904000 	C:\windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
0x548f0000 - 0x548f4000 	C:\windows\system32\api-ms-win-crt-convert-l1-1-0.dll
0x70830000 - 0x7091b000 	C:\windows\system32\dbghelp.dll

VM Arguments:
jvm_args: -Djava.library.path=c:\projects_local\jnano32\build\c\sharedlibrary 
java_command: org.nanomsg.Tester ${args}
java_class_path (initial): c:\projects_local\jnano32\build\java\jar\jnano-0.1-sources.jar;c:\projects_local\jnano32\build\java\jar\jnano-0.1.jar
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0_111\
PATH=C:\Program Files (x86)\Java\jdk1.8.0_111\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Lenovo\Touch Fingerprint Software\;C:\Program Files (x86)\Common Files\Lenovo;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Inductive Automation\Ignition;C:\Program Files\apache-maven-3.3.9\bin;C:\Program Files\apache-ant-1.9.7\bin;C:\Program Files\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;C:\projects_local\jnano32\build\c\sharedlibrary;C:\Program Files (x86)\nanomsg\bin
USERNAME=Florin.T
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7601 (6.1.7601.19160)

CPU:total 8 (4 cores per cpu, 2 threads per core) family 6 model 94 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 16638996k(12591008k free), swap 33276156k(28803332k free)

vm_info: Java HotSpot(TM) Client VM (25.111-b14) for windows-x86 JRE (1.8.0_111-b14), built on Sep 22 2016 18:54:33 by "java_re" with MS VC++ 10.0 (VS2010)

time: Mon Nov 21 11:55:38 2016
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by gonzus** [comment]
Just a hunch, from these two lines:

```
EBX={method} {0x1504411c} 'load_symbols' '(Ljava/util/Map;)I' in 'org/nanomsg/NanoLibrary'
Event: 0.016 Thread 0x00418800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x04807990) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share
```

I would guess there might have been a change in Map? Something that used to work before in Java pre-8, but in Java 8 fails? Maybe a use of Map from the C side that makes assumptions that are not valid anymore?

Again, it has been years since I even looked at this code. Sorry I cannot be of more assistance.

**Comment by florint1** [comment]
I tried JVM 1.7.21 still crashes. I am goint to try compiling against the old nano.

Here is the crash message:

#A fatal error has been detected by the Java Runtime Environment:

#EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x73a21c44, pid=16920, tid=16444

#JRE version: 7.0_21-b11
#Java VM: Java HotSpot(TM) Client VM (23.21-b01 mixed mode, sharing windows-x86 )
#Problematic frame:
#C  [jnano.dll+0x1c44]  Java_org_nanomsg_NanoLibrary_load_1symbols+0x2b4

**Comment by florint1** [comment]
The update  by @prabg fixes the issue. Thank you!
